<html>
<head>
    <meta charset="utf-8">
    <title>My Books</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
<a class="btn btn-default" href="<?= $_SERVER['PHP_SELF'] ?>?reload=Amazon" role="button">Reload Amazon</a><br>
<pre class="text-center"><?= count($this->books) ?> entries</pre>
<table class="table table-striped table-bordered table-condensed">
    <?php foreach ($this->books as $book) { ?>
        <?php $sjw = $book['SJ'] ? "bold" : "normal";
        $scw = $book['SC'] ? "bold" : "normal"; ?>
        <tr>
            <td><?= $book['author'] ?></td>
            <td><a href="<?= $book['amazon'] ?>"><?= $book['title'] ?></a></td>
            <td>
                <?php
                if (count($book['isbns']) < 2) {
                    echo $book['ISBN'];
                } else {
                    echo $this->formSelect("b" . $book['ISBN'], 0, array(), $book['isbns']);
                }
                ?>
            </td>
            <td class="<?= $book['SJ'] ? "success" : ""; ?>">
                <a href="http://mill1.sjlibrary.org/search/i<?= $book['SJ'] ? $book['SJ'] : $book['ISBN'] ?>">SJ</a>
                <a href="http://mill1.sjlibrary.org/search~S1/?searchtype=t&searcharg=<?= rawurlencode($book['title']) ?>&searchscope=1&sortdropdown=-&SORT=D&extended=0&SUBMIT=Search&searchlimits=&searchorigarg=t<?= rawurlencode($book['title']) ?>">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                <a href="https://www.goodreads.com/book/show/<?= $book['GR'] ?>"><span class="glyphicon glyphicon-globe"
                                                                                       aria-hidden="true"></span></a>
            </td>
            <!-- td width="80">
<a href="http://146.74.92.18/ipac20/ipac.jsp?index=ISBNEX&term=<?= $book['SC'] ? $book['SC'] : $book['ISBN'] ?>"  style="font-weight: <?= $scw ?>">Cupertino</a>
</td -->
        </tr>
    <?php } ?>
</table>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>
